### PR TITLE
Adding toYaml, fromYaml functions

### PR DESCRIPTION
**Pull request by alexsorkin**
Useful YAML rendering functions

### CODE REVIEW

**Comment by alexsorkin** [comment]
This will allow to render a block as is, regardless schema:

{{- if has .input "trigger" }}
{{- with .input.trigger }}
trigger: 
{{ . | toYaml | indent 2 }}
{{- end }}
{{- end }}

**Comment by ShruthiHubb** [comment]
Hey @alexsorkin Thanks for submitting your proposal, we appreciate it. 🚀

We usually review PRs every Tuesday and I will keep you up to date if anything changes.

**Comment by eoinmcafee00** [comment]
hey @alexsorkin 

Thank you for your submissions. Would it be possible for you to add a unit test for this, please? Then I'll get it merged.

**Comment by alexsorkin** [comment]
=== RUN   TestToYAML
=== RUN   TestToYAML/toYaml_string
--- PASS: TestToYAML (0.00s)
    --- PASS: TestToYAML/toYaml_string (0.00s)

**Review by eoinmcafee00 — APPROVED** [review]

**Pull request merged**
